
export const FOOTBALL_PLAYERS = [
  'Lionel Messi', 'Cristiano Ronaldo', 'Neymar Jr', 'Kylian Mbappé', 'Robert Lewandowski', 'Kevin De Bruyne', 'Luka Modrić', 'Sergio Ramos', 'Virgil van Dijk', 'Sadio Mané',
  'Mohamed Salah', 'Karim Benzema', 'Erling Haaland', 'Zlatan Ibrahimović', 'Andrés Iniesta', 'Xavi Hernández',
  'Wayne Rooney', 'Frank Lampard', 'Steven Gerrard', 'John Terry', 'Didier Drogba', 'Eden Hazard', 'Thibaut Courtois', 'Jan Oblak',
  'Manuel Neuer', 'Iker Casillas', 'Gianluigi Buffon', 'Giorgio Chiellini', 'Leonardo Bonucci', 'Andrea Pirlo', 'Francesco Totti', 'Daniele De Rossi', 'Paulo Dybala', 'Ángel Di María',
  'Antoine Griezmann', 'Sergio Busquets', 'Jordi Alba', 'Gerard Piqué', 'David Villa', 'Fernando Torres', 'David Silva', 'Cesc Fàbregas',
  'Mesut Özil', 'Toni Kroos', 'Thomas Müller', 'Philipp Lahm', 'Bastian Schweinsteiger', 'Arjen Robben', 'Franck Ribéry', 'Joshua Kimmich', 'İlkay Gündoğan', 'Bernardo Silva',
  'Riyad Mahrez', 'Raheem Sterling', 'Harry Kane', 'Heung-min Son', 'Marcus Rashford', 'Bruno Fernandes', 'Casemiro', 'Vinícius Júnior', 'Rodrygo', 'Federico Valverde',
  'Marco Reus', 'Pierre-Emerick Aubameyang', 'Alexis Sánchez', 'Arturo Vidal', 'James Rodríguez', 'Radamel Falcao', 'Juan Cuadrado', 'Edinson Cavani',
  'Luis Suárez', 'Diego Godín', 'Lautaro Martínez', 'Javier Zanetti', 'Carlos Tevez', 'Sergio Agüero',
  'Yaya Touré', 'David Alaba', 'Marcelo', 'Dani Alves', 'Thiago Silva', 'Marquinhos', 'N\'Golo Kanté', 'Paul Pogba', 'Kingsley Coman', 'Achraf Hakimi',
  'Yassine Bounou', 'Hakim Ziyech', 'Kalidou Koulibaly', 'Victor Osimhen', 'Khvicha Kvaratskhelia', 'Jude Bellingham', 'Bukayo Saka', 'Martin Ødegaard', 'Declan Rice', 'Rodri',
  'Alisson Becker', 'Ederson', 'Marc-André ter Stegen', 'Keylor Navas'
];

export const FAMOUS_MOVIES = [
  'El Padrino', 'Batman: El Caballero de la Noche', 'Forrest Gump',
  'The Matrix', 'Star Wars', 'Titanic', 'Jurassic Park', 'Avengers: Endgame',
  'El Rey León (Animada)',
  'Toy Story',
  'Shrek',
  'Frozen',
  'Buscando a Nemo',
  'Coco',
  'Intensa-Mente',
  'El viaje de Chihiro',
  'Mi Villano Favorito',
  'Spider-Man: Un nuevo universo',
  'Up: Una aventura de altura',
  'Los Increíbles',
  'Ratatouille',
  'Aladdín (Animada)',
  'La Sirenita (Animada)',
  'La Bella y la Bestia (Animada)',
  'Harry Potter',
  'El Señor de los Anillos',
  'Volver al Futuro',
  'E.T. el Extraterrestre',
  'Indiana Jones',
  'Avatar',
  'Gladiador',
  'Interestelar',
  'Parásitos',
];

export const UNIVERSITY_MAJORS = [
  'Ingeniería de Sistemas',
  'Medicina',
  'Derecho',
  'Administración de Empresas',
  'Psicología',
  'Arquitectura',
  'Ingeniería Civil',
  'Diseño Gráfico',
  'Economía',
  'Periodismo',
  'Contabilidad',
  'Marketing',
  'Enfermería',
  'Ingeniería Industrial',
  'Ingeniería Química',
  'Biología',
  'Física',
  'Química',
  'Matemáticas',
  'Estadística',
  'Filosofía',
  'Historia',
  'Sociología',
  'Antropología',
  'Ciencias Políticas',
  'Relaciones Internacionales',
  'Recursos Humanos',
  'Comercio Internacional',
  'Ingeniería Mecánica',
  'Ingeniería Eléctrica',
  'Ingeniería Electrónica',
  'Odontología',
  'Farmacia',
  'Nutrición y Dietética',
  'Veterinaria',
  'Educación',
  'Idiomas Modernos',
  'Traducción e Interpretación',
  'Literatura',
  'Arte Dramático (Teatro)',
  'Música',
  'Cine y Televisión',
  'Diseño de Modas',
  'Diseño Industrial',
  'Geología',
  'Ingeniería Ambiental',
  'Ciencias de la Computación',
  'Gastronomía',
  'Comunicación Social',
  'Publicidad',
];

export const DISNEY_CHARACTERS = [
  'Mickey Mouse',
  'Elsa (Frozen)',
  'Simba (El Rey León)',
  'Woody (Toy Story)',
  'Buzz Lightyear',
  'Moana',
  'Aladdín',
  'La Sirenita (Ariel)',
  'Stitch',
  'Peter Pan',
  'Pato Donald',
  'Goofy',
  'Minnie Mouse',
  'Cenicienta',
  'Bella (La Bella y la Bestia)',
  'Bestia (La Bella y la Bestia)',
  'Blancanieves',
  'Aurora (La Bella Durmiente)',
  'Mulán',
  'Pocahontas',
  'Rapunzel',
  'Tiana (La Princesa y el Sapo)',
  'Jasmín (Aladdín)',
  'Genio (Aladdín)',
  'Timón (El Rey León)',
  'Pumba (El Rey León)',
  'Nemo (Buscando a Nemo)',
  'Dory (Buscando a Nemo)',
  'Rayo McQueen',
  'Mate (Cars)',
  'Mike Wazowski (Monsters, Inc.)',
  'Sully (Monsters, Inc.)',
  'Wall-E',
  'Eva (Wall-E)',
  'Mr. Increíble',
  'Elastigirl',
  'Jack Sparrow',
  'Capitán Garfio',
  'Maléfica',
  'Úrsula (La Sirenita)',
  'Jafar (Aladdín)',
  'Scar (El Rey León)',
  'Cruella de Vil',
  'Hades (Hércules)',
  'Hércules',
  'Tarzán',
  'Lilo (Lilo y Stitch)',
  'Pinocho',
  'Pepito Grillo',
  'Dumbo',
  'Bambi',
  'Alicia (País de las Maravillas)',
  'Sombrerero Loco',
  'Winnie Pooh',
  'Tigger',
  'Mowgli (El Libro de la Selva)',
  'Baloo (El Libro de la Selva)',
  'Olaf (Frozen)',
  'Anna (Frozen)',
];

export const FAMOUS_LANDMARKS = [
  'Torre Eiffel',
  'Estatua de la Libertad',
  'Coliseo Romano',
  'Gran Muralla China',
  'Machu Picchu',
  'Pirámides de Giza',
  'Taj Mahal',
  'Cristo Redentor',
  'Chichén Itzá',
  'Acrópolis de Atenas',
  'Monte Everest',
  'Cataratas del Niágara',
  'Canal de Panamá',
  'Isla de Pascua (Moáis)',
  'Petra',
  'Torre de Pisa',
];

export const SOCIAL_APPS = [
  'WhatsApp',
  'Instagram',
  'TikTok',
  'Facebook',
  'YouTube',
  'Twitter (X)',
  'Spotify',
  'Netflix',
  'Telegram',
  'LinkedIn',
];

export const FAMOUS_TV_SERIES = [
  'Friends',
  'Stranger Things',
  'Juego de Tronos',
  'Los Simpson',
  'Breaking Bad',
  'La Casa de Papel',
  'El Juego del Calamar',
  'The Office',
  'Black Mirror',
  'The Mandalorian',
];

export const THEME_LISTS = {
  'Football Players': FOOTBALL_PLAYERS,
  'Famous Movies': FAMOUS_MOVIES,
  'University Majors': UNIVERSITY_MAJORS,
  'Disney Characters': DISNEY_CHARACTERS,
  'Famous Landmarks': FAMOUS_LANDMARKS,
  'Social Apps': SOCIAL_APPS,
  'Famous TV Series': FAMOUS_TV_SERIES,
};
